# Documentation:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/' # Location of package manifests.
      schedule:
          interval: 'weekly'
    # Check for updates to GitHub Actions every week
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
